### PR TITLE
Updated 3 methods to resolve issues

### PR DESCRIPTION
**Pull request by kritgrover**
- Adds new experience, skill or education and return index
- Returns specific experience, skill or education
- Returns list of experience, skill or education

### CODE REVIEW

**Comment by wrussell1999** [comment]
In future @kritgrover, make sure to reference the issues you've implemented:
- https://github.com/MLH-Fellowship/orientation-project-python-23.SUM.A/issues/22 
- https://github.com/MLH-Fellowship/orientation-project-python-23.SUM.A/issues/21
- https://github.com/MLH-Fellowship/orientation-project-python-23.SUM.A/issues/20
- https://github.com/MLH-Fellowship/orientation-project-python-23.SUM.A/issues/19
- https://github.com/MLH-Fellowship/orientation-project-python-23.SUM.A/issues/18
- https://github.com/MLH-Fellowship/orientation-project-python-23.SUM.A/issues/17
- https://github.com/MLH-Fellowship/orientation-project-python-23.SUM.A/issues/16
- https://github.com/MLH-Fellowship/orientation-project-python-23.SUM.A/issues/15
- https://github.com/MLH-Fellowship/orientation-project-python-23.SUM.A/issues/14

Some fellows had already started contributing to them as they thought no one else had assigned themselves. In future, make sure to assign yourself to avoid duplicate work!

**Comment by kritgrover** [comment]
sure, i'll make the changes and keep that in mind!

**Comment by Henoven** [comment]
Hey well done! @kritgrover 
I see you're on fire with issues. I agree with @wrussell1999 and I wanted to give you another suggestion. Normally submit PR per issue but in this case it makes sense to do all together : )

**Comment by wrussell1999** [comment]
@kritgrover looking good with the tests. Can you write one last test:
- Add a new experience and get the index.
- Make a request with that index and check it returns the same JSON

**Review by wrussell1999 — APPROVED** [review]
Looks great, good stuff!

**Comment by kritgrover** [comment]
Hey @wrussell1999, sorry for that! Just submitted the new PR with the required changes.

**Pull request merged**
