### PR TITLE
Separated logic into utils file and fixed indexing bug

### PR DESCRIPTION
**Pull request by ahmedehabb**
I separated the logic of getting a certain model by index into functions in a separate file called utils.py since i will use the same code in editing existing models.
Also there is a bug in indexing (if 0 <= index < len(data["education"]) -1 ) this will exclude the last one which is incorrect.
so i removed the -1

### CODE REVIEW

**Comment by ahmedehabb** [comment]
i still get linter error due to the functions in app.py not returning something outside of the if conditions.
should I add return jsonify({}) as a last statement in each function.

**Comment by ahmedehabb** [comment]
when #25 get approved, I will pull the new changes and update this pr to solve linter issues.

**Comment by wrussell1999** [comment]
Hey @ahmedehabb! #25 is all merged in now, so you're good to now complete the following:

- [ ] Resolve merge conflicts in `app.py`.
- [ ] Run the linter and update the style of your code

**Comment by wrussell1999** [comment]
@ahmedehabb looks all good. Final thing to get it approved would be to update in the README what the purpose of the `utils.py` so future people know what to put in there!

**Review by wrussell1999 — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
