### PR TITLE
Feat/post request validation

### PR DESCRIPTION
**Pull request by Raajheer1**
Issue #13 
Added post request validation right now it ensures the body has the required keys and that they're in the correct datatype.

### CODE REVIEW

**Review by wrussell1999 — COMMENTED** [review]
Looks good. Is there a way to use the `utils.py` to reduce the amount of repeated code between the Experience, Education and Skill functions? @Raajheer1

**Comment by wrussell1999** [comment]
@Raajheer1 in future, make sure to comment on the issue before starting on it to prevent others duplicating code

**Comment by Raajheer1** [comment]
@wrussell1999 There is! I changed the required fields to a dict and moved the request validation into its own function in [1c92f96](https://github.com/MLH-Fellowship/orientation-project-python-23.SUM.A/pull/29/commits/1c92f961305fc16618074c4c25d2f6edbb2431e4)

The only datatype being used is a string however I added support for integers as well as an example of how to extend the function to support other datatypes.

**Review by wrussell1999 — APPROVED** [review]
Looking great!

**Pull request merged**
