### PR TITLE
Edit existing experience by passing fields to be updated

### PR DESCRIPTION
**Pull request by ahmedehabb**
handling this issue #8

### CODE REVIEW

**Comment by wrussell1999** [comment]
Hey @ahmedehabb! Looking good, can you resolve the conflicts then I'll approve!

**Comment by ahmedehabb** [comment]
successfully merged the conflicts.
But I had to separate the logic for each type of request [get, post, put] into a separate function because of the linter issues as we had many return statements before

**Review by wrussell1999 — APPROVED** [review]
I like how you've split the code up so it's easier to follow!

**Comment by ahmedehabb** [comment]
Wow! thank you :)

**Pull request merged**
