### PR TITLE
Updated styling for pylint

### PR DESCRIPTION
**Pull request by kritgrover**

### CODE REVIEW

**Comment by wrussell1999** [comment]
Hey @kritgrover, in future make sure to add a clear description to the PR, and also referencing the other PR to show the link. Helps others know the context too!

This resolves the linting in https://github.com/MLH-Fellowship/orientation-project-python-23.SUM.A/pull/24

**Comment by kritgrover** [comment]
Hey @wrussell1999. Noted, will keep that in mind.

**Comment by wrussell1999** [comment]
@kritgrover final thing for approval is adding a message for the new return statement. Aside from that, looks good!

**Comment by kritgrover** [comment]
Hey @wrussell1999, I have added the message to the return statements.

**Review by wrussell1999 — APPROVED** [review]

**Pull request merged**
